<a href="https://colab.research.google.com/github/ellricadhj/Machine-Learning/blob/master/Practice_of_LDA_PC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# PC1



## Importing the dataset

In [23]:
dataset = pd.read_csv('PC1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

##SMOTE

In [25]:
from imblearn.over_sampling import SMOTE
smote = SMOTE('minority')

X_sm_train, y_sm_train = smote.fit_sample(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


## Applying LDA

In [26]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_sm_lda_train = lda.fit_transform(X_sm_train, y_sm_train)
X_test = lda.transform(X_test)

## LogReg

In [27]:
from sklearn.linear_model import LogisticRegression
logregclassifier = LogisticRegression(random_state = 0)
logregclassifier.fit(X_sm_lda_train, y_sm_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = logregclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[167  39]
 [  6  10]]
0.7972972972972973
              precision    recall  f1-score   support

       False       0.97      0.81      0.88       206
        True       0.20      0.62      0.31        16

    accuracy                           0.80       222
   macro avg       0.58      0.72      0.59       222
weighted avg       0.91      0.80      0.84       222



## SVM

In [29]:
from sklearn.svm import SVC
svmclassifier = SVC(kernel = 'linear', random_state = 0)
svmclassifier.fit(X_sm_lda_train, y_sm_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = svmclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[167  39]
 [  5  11]]
0.8018018018018018
              precision    recall  f1-score   support

       False       0.97      0.81      0.88       206
        True       0.22      0.69      0.33        16

    accuracy                           0.80       222
   macro avg       0.60      0.75      0.61       222
weighted avg       0.92      0.80      0.84       222



## Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier
rfclassifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
rfclassifier.fit(X_sm_lda_train, y_sm_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = rfclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[163  43]
 [  4  12]]
0.7882882882882883
              precision    recall  f1-score   support

       False       0.98      0.79      0.87       206
        True       0.22      0.75      0.34        16

    accuracy                           0.79       222
   macro avg       0.60      0.77      0.61       222
weighted avg       0.92      0.79      0.84       222

